---
project:
  fqdn: example.com
  name: examplecom
  user: examplecom
  group: www-data
  mode: live
  branch: develop
  repo: ssh://git@git.example.com:1234/examplecom.git
  root: /var/www/virtualhosts/examplecom/

nginx:
  servernames:
    - "*.example.com"
    - "example.com"

django:
  settings: base.settings.live
  wsgi: base.wsgi
  root: ${project.root}/code/application
  virtualenv: ${project.root}/environ
  fixtures:
    - ${django.root}/base/fixtures/${project.mode}.json
    - ${django.root}/base/fixtures/users.json
    - ${django.root}/base/fixtures/pages.json

database:
  user: examplecom
  password: some-random-password
  name: examplecom
  host: localhost
  port: 1234

message_queue:
  redis_id: 2

cache:
  redis_id: 1
