---
- name: Celery | Install Celery upstart jobs
  template: >
    src=upstart.celeryd.conf.j2
    dest=/etc/init/{{project.name}}_celeryd.conf
  notify:
    - restart celery
  tags:
    - celery

- name: Celery | Install CeleryBeat upstart jobs
  template: >
    src=upstart.celerybeat.conf.j2
    dest=/etc/init/{{project.name}}_celerybeat.conf
  notify:
    - restart celerybeat
  tags:
    - celery