---
- name: Commmon | Create the SSL directory.
  file: >
    state=directory
    path=/etc/nginx/ssl/
  tags:
    - configuration
    - ssl

- name: Commmon | Upload SSL private key.
  copy: >
    src=${nginx.ssl.private}
    dest=/etc/nginx/ssl/${project.name}-private
  tags:
    - configuration
    - ssl

- name: Commmon | Upload SSL public key.
  copy: >
    src=${nginx.ssl.public}
    dest=/etc/nginx/ssl/${project.name}-public
  tags:
    - configuration
    - ssl
