---
- name: uWsgi | (apt) Install required system packages.
  apt: >
    pkg=${item}
    state=installed
    update-cache=yes
  with_items:
    - build-essential
    - uwsgi
  tags:
    - packages
    - provision

- name: uWsgi | (pip) Install required system packages.
  pip: name=$item
  with_items:
    - pip
    - virtualenv
    - uwsgi
  tags:
    - packages
    - provision
