---
- name: Commmon | Install required system packages.
  apt: >
    pkg=${item}
    state=installed
    update-cache=yes
  with_items:
    - build-essential
    - uwsgi
  tags:
    - packages
    - provision
