---
- name: Listen on public interface
  lineinfile: >
    dest=/etc/redis/redis.conf
    regexp="^bind"
    line="#bind"
  notify: restart redis
    # line="#bind = '{{ groups.get('dbservers')[0] }}'"
