---
- name: Django | Assets | Compress
  sudo_user: ${project.user}
  shell: command=". ${project.virtualenv}bin/activate; cd ${django.root}; python ./manage.py compress --settings=${django.settings} --force"
  tags:
    - assets
    - collectstatic
    - update
    - application
    - django

- name: Django | Assets | Collect
  sudo_user: ${project.user}
  django_manage: >
    command=collectstatic
    link=yes
    app_path=${django.root}
    settings=${django.settings}
    virtualenv=${project.virtualenv}
  tags:
    - assets
    - collectstatic
    - update
    - application
    - django
  notify:
    - restart nginx
    - restart uwsgi