---
- name: Django | Create Project root directory.
  file: >
    state=directory
    path=${project.root}
    group=www-data
    owner=www-data
    mode=755
    state=directory
  tags:
    - base
    - provision

- name: Users | Create user.
  user: >
    home=${project.root}/home
    name=${project.user}
    state=present
    groups=www-data
  tags:
    - base
    - provision

- name: Users | Change Permissions.
  shell: chown -R ${project.user}:${project.group} ${project.root}
  tags: base

