---
- name: Git | Pull sources from the repository.
  sudo: yes
  sudo_user: ${project.user}
  git: >
    repo=${project.repo}
    dest=${project.root}/code
    version=${project.branch}
    depth=1
  tags:
    - repo
    - application

