---
- name: Users | Create user.
  user: >
    home=${project.root}/home
    name=${project.user}
    state=present
    groups=www-data
  tags:
    - base
    - provision

- name: Users | Change Permissions.
  shell: chown -R ${project.user}:${project.group} ${project.root}
  tags: base

