---
- name: Create Database User
  when: not project.is_local
  sudo_user: postgres
  postgresql_user: user=${database.user}
                   password=${database.password}
                   role_attr_flags=CREATEDB,NOSUPERUSER
  tags: database

- name: Create Database.
  when: not project.is_local
  sudo_user: postgres
  postgresql_db: name=${database.name} owner=${database.user}
                 login_host=${database.host}
                 login_user=${database.user}
                 login_password=${database.password}
  tags:
    - database
    - create
